// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DmBuddyDatabase
{
    public partial class AspNetRoles
    {
        public AspNetRoles()
        {
            LoginTerminations = new HashSet<LoginTerminations>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string NormalizedName { get; set; }
        public string ConcurrencyStamp { get; set; }

        public virtual ICollection<LoginTerminations> LoginTerminations { get; set; }
    }
}