// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DmBuddyDatabase;

public partial class LoginTerminations
{
    public DateTime TerminationDate { get; set; }

    public string RoleId { get; set; }

    public string LoginId { get; set; }

    public virtual AspNetUsers Login { get; set; }

    public virtual AspNetRoles Role { get; set; }
}