// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DmBuddyDatabase
{
    public partial class TblLogins
    {
        public Guid LoginId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Access { get; set; }
        public DateTime? TerminationDate { get; set; }
    }
}